services:
  tessellations:
    build: .
    volumes:
      - .:/app
      - ~/Documents/tessellations:/app/output
    environment:
      - PYTHONPATH=/app
    command: tessellate --output-dir /app/output --format svg